apiVersion: v1
kind: Service
metadata:
  name: test-workflow02-k8s
  namespace: namespace-workflow-1709974034803
spec:
  type: LoadBalancer
  selector:
    app: test-workflow02-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80